feat: Leverage sidecar feature to allow Python version flexibility
Signed-off-by: Ilona Shishov <Ilona.Shishov@gmail.com>

diff --git a/task/redhat-dependency-analytics/0.2/redhat-dependency-analytics.yaml b/task/redhat-dependency-analytics/0.2/redhat-dependency-analytics.yaml
--- a/task/redhat-dependency-analytics/0.2/redhat-dependency-analytics.yaml
+++ b/task/redhat-dependency-analytics/0.2/redhat-dependency-analytics.yaml
@@ -28,13 +28,51 @@ spec:
       description: Path to file within workspace, where the analysis report is saved.
       default: redhat-dependency-analytics-report.json
 
-    - name: image
+    - name: rhda-image
       description: Image where Exhort Javascript API and required dependencies are installed.
-      default: quay.io/ecosystem-appeng/exhort-javascript-api:0.7.3-alpha
+      default: quay.io/ecosystem-appeng/exhort-javascript-api:0.1.1-ea.14
+
+    - name: python-image
+      description: Image with installed Python interpreter and associated tools (such as pip, pip3, etc.).
+      default: python:3.11
+
+  sidecars:
+    - name: python
+      image: $(params.python-image)
+      volumeMounts:
+        - mountPath: /shared
+          name: shared-data
+      script: |
+        #!/bin/sh
+        
+        # Function to handle errors
+        handle_error() {
+            cp error.log /shared/error.log
+            exit 1
+        }
+        
+        # Wait for a Step to supply the sidecar with requirements file.
+        while [ ! -f /shared/requirements.txt ] ; do
+          if [ -f /shared/notPython ]; then
+            exit 0
+          fi
+          sleep 1
+        done
+
+        python -m venv /tmp 2>error.log || handle_error
+
+        /tmp/bin/pip3 install -r /shared/requirements.txt 2>error.log || handle_error
+
+        /tmp/bin/pip3 freeze --all > /shared/pip_freeze.txt 2>error.log || handle_error
+
+        SHOW_LIST=$(awk -F '==' '{print $1}' < /shared/pip_freeze.txt)
+        /tmp/bin/pip3 show $(echo "$SHOW_LIST") > /shared/pip_show.txt 2>error.log || handle_error
+
+        touch /shared/pythonComplete
 
   steps:
     - name: redhat-dependency-analytics
-      image: $(params.image)
+      image: $(params.rhda-image)
       workingDir: $(workspaces.output.path)
       env:
         - name: EXHORT_SNYK_TOKEN
@@ -44,9 +82,28 @@ spec:
               key: EXHORT_SNYK_TOKEN
         - name: RHDA_SOURCE
           value: tekton
+      volumeMounts:
+        - mountPath: /shared
+          name: shared-data
       script: |
-        #!/bin/sh
-        
+        #!/bin/sh    
+
+        # Function to handle errors
+        handle_error() {
+            # Save exit code into output file.
+            jq -n {} | jq --arg exit_code "1" '. + {exit_code: $exit_code}' > $OUTPUT_FILE_PATH
+
+            # Print stderr message to console
+            error_message=$(sed -n '/^ERROR:/p' error.log)
+            printf "\n[ERROR] Failed to install dependencies from requirements.txt.\n$error_message"
+
+            exit 1
+        }
+
+        # Set the timeout duration in seconds
+        timeout_duration=60
+        elapsed_time=0
+
         # get task parameter values
         MANIFEST_FILE_PATH="$(params.manifest-file-path)"
         OUTPUT_FILE_PATH="$(params.output-file-path)"
@@ -54,20 +111,36 @@ spec:
         # install dependencies for requirements.txt file
         MANIFEST_FILE_BASENAME=$(basename "$MANIFEST_FILE_PATH")
         if [ "$MANIFEST_FILE_BASENAME" = "requirements.txt" ]; then
-          pip3 install -r $MANIFEST_FILE_PATH 2>error.log >/dev/null
-          exit_code=$?
-          if [ $exit_code != 0 ]; then
-            # In case of failure save only exit code into output file.
-            jq -n {} | jq --arg exit_code "$exit_code" '. + {exit_code: $exit_code}' > $OUTPUT_FILE_PATH
+          cp $MANIFEST_FILE_PATH /shared/requirements.txt
 
-            # Print stderr message to console and exit
-            error_message=$(sed -n '/^ERROR:/p' error.log)
-            printf "\n[ERROR] Failed to install dependencies from requirements.txt with exit code $exit_code.\n$error_message"
-            exit 1
-          fi
+          # Wait for sidecar to provide dependency data.
+          while [ ! -f /shared/pip_show.txt ] || [ ! -f /shared/pip_freeze.txt ] || [ ! -f /shared/pythonComplete ] ; do
+            
+            # Check if error occured
+            if [ -f /shared/error.log ]; then
+              cp /shared/error.log .  
+              handle_error
+            fi
+            
+            # Check if the timeout is reached
+            if [ "$elapsed_time" -ge "$timeout_duration" ]; then
+                echo "Timeout reached." > error.log
+                handle_error
+            fi
+
+            sleep 1
+            ((elapsed_time++))
+          done
+
+          export EXHORT_PIP_FREEZE=$(cat /shared/pip_freeze.txt | base64 -w 0)
+          export EXHORT_PIP_SHOW=$(cat /shared/pip_show.txt | base64 -w 0)
+        else
+          touch /shared/notPython
         fi
 
         # execute RHDA
         sh /rhda.sh "$MANIFEST_FILE_PATH" "$OUTPUT_FILE_PATH"
 
-
+  volumes:
+    - name: shared-data
+      emptyDir: {}
